service: blog-users-serverless
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: '2.0'
    authorizers:
      adminAuthorizer:
        type: request
        functionName: adminAuthorizer
        identitySource:
          - $request.header.Authorization

  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  tracing:
    lambda: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    NODE_PATH: "./:/opt/node_modules"
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASS: ${env:DATABASE_PASS}
    DATABASE_NAME: ${env:DATABASE_NAME}
    APP_SECRET: ${env:APP_SECRET}
    CLIENT_URL: ${env:CLIENT_URL}

functions:

  healthCheck:
    handler: src/functions/health-check/index.healthCheck
    events:
      - httpApi: 'GET /dev/health-check'
    memorySize: 128
    tracing: Active

  createUser:
    handler: src/functions/user/create/index.createUser
    events:
      - httpApi: 'POST /dev/create-user'
    memorySize: 128
    tracing: Active

  listUsers:
    handler: src/functions/user/list/index.listUsers
    events:
      - httpApi: 'GET /dev/users'
    memorySize: 128
    tracing: Active

  readUser:
    handler: src/functions/user/read/index.readUser
    events:
      - httpApi: 'GET /dev/user'
    memorySize: 128
    tracing: Active

  updateRoleUser:
    handler: src/functions/user/updateRole/index.updateRoleUser
    events:
      - http:
          path: /update-user-role
          method: put
          authorizer: adminAuthorizer
    memorySize: 128
    tracing: Active


  updateUser:
    handler: src/functions/user/update/index.updateUser
    events:
      - httpApi: 'PUT /dev/update-user'
    memorySize: 128
    tracing: Active

  forgotPassword:
    handler: src/functions/user/forgotPassword/index.forgotPassword
    events:
      - httpApi: 'POST /dev/forgot-password'
    memorySize: 128
    tracing: Active

  resetPassword:
    handler: src/functions/user/resetPassword/index.resetPassword
    events:
      - httpApi: 'POST /dev/reset-password'
    memorySize: 128
    tracing: Active

  login:
    handler: src/functions/session/login/index.login
    events:
      - httpApi: 'POST /dev/login'
    memorySize: 128
    tracing: Active

  checkin:
    handler: src/functions/session/checkin/index.checkin
    events:
      - httpApi: 'POST /dev/check-in'
    memorySize: 128
    tracing: Active

  logout:
    handler: src/functions/session/logout/index.logout
    events:
      - httpApi: 'DELETE /dev/logout'
    memorySize: 128
    tracing: Active

  authorizer:
    handler: src/functions/auth/authorizer/index.authorizer

  adminAuthorizer:
    handler: src/functions/auth/adminAuthorizer/index.adminAuthorizer

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-dotenv-plugin

package: 
  individually: true
  exclude: 
    - node_modules
