service: blog-users-serverless
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: '2.0'
    authorizers:
      adminAuthorizer:
        type: request
        functionName: adminAuthorizer
        identitySource:
          - $request.header.Authorization
      authorizer:
        type: request
        functionName: authorizer
        identitySource:
          - $request.header.Authorization

  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  tracing:
    lambda: true # enable tracing
  iam:
    role:
      statements:
        - Effect: "Allow" # xray permissions (required)
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    NODE_PATH: "./:/opt/node_modules"
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASS: ${env:DATABASE_PASS}
    DATABASE_NAME: ${env:DATABASE_NAME}
    APP_SECRET: ${env:APP_SECRET}
    CLIENT_URL: ${env:CLIENT_URL}

functions:


  healthCheck:
    handler: src/functions/health-check/index.healthCheck
    events:
      - http:
          path: /health-check
          method: get
    memorySize: 128
    tracing: Active


  createUser:
    handler: src/functions/user/create/index.createUser
    events:
      - http:
          path: /create-user
          method: post
    memorySize: 128
    tracing: Active


  listUsers:
    handler: src/functions/user/list/index.listUsers
    events:
      - http:
          path: /user
          method: get
          authorizer: adminAuthorizer
    memorySize: 128
    tracing: Active


  readUser:
    handler: src/functions/user/read/index.readUser
    events:
      - http:
          path: /user/{user}
          method: get
    memorySize: 128
    tracing: Active


  updateRoleUser:
    handler: src/functions/user/updateRole/index.updateRoleUser
    events:
      - http:
          path: /update-user-role/{user}
          method: put
          authorizer: adminAuthorizer
    memorySize: 128
    tracing: Active


  updateUser:
    handler: src/functions/user/update/index.updateUser
    events:
      - http:
          path: /update-user/{user}
          method: put
          authorizer: authorizer
    memorySize: 128
    tracing: Active


  forgotPassword:
    handler: src/functions/user/forgotPassword/index.forgotPassword
    events:
      - http:
          path: /forgot-password
          method: post
    memorySize: 128
    tracing: Active


  resetPassword:
    handler: src/functions/user/resetPassword/index.resetPassword
    events:
      - http:
          path: /reset-password
          method: post
    memorySize: 128
    tracing: Active


  login:
    handler: src/functions/session/login/index.login
    events:
      - http:
          path: /login
          method: post
    memorySize: 128
    tracing: Active


  checkin:
    handler: src/functions/session/checkin/index.checkin
    events:
      - http:
          path: /check-in
          method: post
    memorySize: 128
    tracing: Active


  logout:
    handler: src/functions/session/logout/index.logout
    events:
      - http:
          path: /logout/{user}
          method: delete
    memorySize: 128
    tracing: Active


  authorizer:
    handler: src/functions/auth/authorizer/index.authorizer

  adminAuthorizer:
    handler: src/functions/auth/adminAuthorizer/index.adminAuthorizer

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-dotenv-plugin

package: 
  individually: true
  exclude: 
    - node_modules

custom:
  serverless-offline:
    httpPort: 5000