service: blog-users-serverless
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: "2.0"
    authorizers:
      adminAuthorizer:
        type: request
        functionName: adminAuthorizer
        identitySource:
          - $request.header.Authorization
      authorizer:
        type: request
        functionName: authorizer
        identitySource:
          - $request.header.Authorization
  deploymentBucket:
    name: "blog-users-serverless-deployment-bucket"

  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  tracing:
    lambda: true # enable tracing
  iam:
    role:
      statements:
        - Effect: "Allow" # xray permissions (required)
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    NODE_PATH: "./:/opt/node_modules"
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASS: ${env:DATABASE_PASS}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_HOST: ${env:DATABASE_HOST}
    APP_SECRET: ${env:APP_SECRET}
    CLIENT_URL: ${env:CLIENT_URL}

functions:
  healthCheck:
    handler: src/functions/health-check/index.healthCheck
    events:
      - http:
          path: /health-check
          method: get
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  createUser:
    handler: src/functions/user/create/index.createUser
    events:
      - http:
          path: /user/
          method: post
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  listUsers:
    handler: src/functions/user/list/index.listUsers
    events:
      - http:
          path: /user/
          method: get
          cors:
            origin: "*"
          authorizer: adminAuthorizer
    memorySize: 128
    tracing: Active

  readUser:
    handler: src/functions/user/read/index.readUser
    events:
      - http:
          path: /user/{user}
          method: get
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  updateRoleUser:
    handler: src/functions/user/updateRole/index.updateRoleUser
    events:
      - http:
          path: /user/role/{user}
          method: put
          cors:
            origin: "*"
          authorizer: adminAuthorizer
    memorySize: 128
    tracing: Active

  updateUser:
    handler: src/functions/user/update/index.updateUser
    events:
      - http:
          path: /update-user/{user}
          method: put
          cors:
            origin: "*"
          authorizer: authorizer
    memorySize: 128
    tracing: Active

  forgotPassword:
    handler: src/functions/user/forgotPassword/index.forgotPassword
    events:
      - http:
          path: /forgot-password
          method: post
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  resetPassword:
    handler: src/functions/user/resetPassword/index.resetPassword
    events:
      - http:
          path: /reset-password
          method: post
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  login:
    handler: src/functions/session/login/index.login
    events:
      - http:
          path: /user/login
          method: post
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  checkin:
    handler: src/functions/session/checkin/index.checkin
    events:
      - http:
          path: /user/check-in
          method: post
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  logout:
    handler: src/functions/session/logout/index.logout
    events:
      - http:
          path: /user/logout/{user}
          method: delete
          cors:
            origin: "*"
    memorySize: 128
    tracing: Active

  authorizer:
    handler: src/functions/auth/authorizer/index.authorizer

  adminAuthorizer:
    handler: src/functions/auth/adminAuthorizer/index.adminAuthorizer

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-dotenv-plugin
  - serverless-deployment-bucket

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 5000
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: "node18"
    define:
      require.resolve: undefined
    platform: "node"
    concurrency: 10
