service: blog-users-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  healthCheck:
    handler: src/functions/health-check/index.healthCheck
    events:
      - httpApi:
          path: /health-check/
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
