service: blog-users-serverless
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: '2.0'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  tracing:
    lambda: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    NODE_PATH: "./:/opt/node_modules"
    DATABASE_USER: ${env:DATABASE_USER}
    DATABASE_PASS: ${env:DATABASE_PASS}
    DATABASE_NAME: ${env:DATABASE_NAME}
    APP_SECRET: ${env:APP_SECRET}
    CLIENT_URL: ${env:CLIENT_URL}

functions:
  healthCheck:
    handler: src/functions/health-check/index.healthCheck
    events:
      - httpApi: 'GET /dev/health-check'
    memorySize: 128
    tracing: Active

  createUser:
    handler: src/functions/user/create/index.createUser
    events:
      - httpApi: 'POST /dev/create-user'
    memorySize: 128
    tracing: Active

  listUsers:
    handler: src/functions/user/list/index.listUsers
    events:
      - httpApi: 'GET /dev/users'
    memorySize: 128
    tracing: Active

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-dotenv-plugin

package: 
  individually: true
  exclude: 
    - node_modules
